### PR TITLE
Match BaseRobot init signature.

### PR DESCRIPTION
**Pull request by mvandermerwe**

### CODE REVIEW

**Comment by mvandermerwe** [comment]
@PeterMitrano have you run the latest stack with victor? I suspect the issue I fix here is also present for Victor.

**Comment by PeterMitrano** [comment]
I don't understand why you need this change. victor and val don't have it, there's already a default for robot_description in base_robot

**Comment by mvandermerwe** [comment]
> I don't understand why you need this change. victor and val don't have it, there's already a default for robot_description in base_robot

It appears that it calls BaseMed's constructor from MoveItEnabledRobot.

**Review by acsipos — APPROVED** [review]
Looks great

**Comment by PeterMitrano** [comment]
ok I see the problem... not sure why my code hasn't hit this error because you're right Victor and Val should have the same problem. Can you add it to them as well?

**Comment by PeterMitrano** [comment]
ok no I take it back I don't get the problem... I can construct a `Val` without any changes... I'm confused

**Comment by PeterMitrano** [comment]
ok I figured out the problem... you have the super classes listed in the wrong order in `Med`. The call to  `super()` inside the constructor for `MoveitEnabledRobot` _should_ call `BaseRobot` not `MedBase`. It should be 


```
class Med(BaseMed, MoveitEnabledRobot):
```

**Comment by mvandermerwe** [comment]
> ok I figured out the problem... you have the super classes listed in the wrong order in `Med`. The call to `super()` inside the constructor for `MoveitEnabledRobot` _should_ call `BaseRobot` not `MedBase`. It should be
> 
> ```
> class Med(BaseMed, MoveitEnabledRobot):
> ```

Good catch - I've fixed this now.

**Pull request merged**
